version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ws_server"
    schedule:
      interval: "weekly"
    target-branch: "main"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    reviewers:
      - "GamingLuke1337"
